name: Run Scraper Daily

on:
  schedule:
    # Chạy scraper mỗi ngày vào lúc 00:00 UTC (7:00 sáng giờ Việt Nam)
    - cron: '0 0 * * *'
  workflow_dispatch: # Cho phép chạy thủ công từ tab Actions của GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout code
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 3. Install dependencies
      run: |
        set -e
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "--- DANH SÁCH THƯ VIỆN ĐÃ CÀI ---"
        pip freeze

    - name: 4. Verify file and environment
      run: |
        echo "--- Python Path ---"
        which python
        echo "--- File List ---"
        ls -la
        
    - name: 5. Run Scraper via Python Module
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        PYTHONUNBUFFERED: "1"
      # *** THAY ĐỔI QUAN TRỌNG: Chạy scraper như một module ***
      # Cách này ổn định hơn và tránh được các lỗi môi trường tiềm ẩn.
      run: python -m scraper
