name: Run Scraper Daily

on:
  schedule:
    # Chạy scraper mỗi ngày vào lúc 00:00 UTC (7:00 sáng giờ Việt Nam)
    - cron: '0 0 * * *'
  workflow_dispatch: # Cho phép chạy thủ công từ tab Actions của GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout code
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 3. Install dependencies
      run: |
        set -e # Dừng lại ngay nếu có lỗi
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install supabase # Cài thêm các thư viện chưa có trong file
        echo "--- DANH SÁCH THƯ VIỆN ĐÃ CÀI ---"
        pip freeze # In ra tất cả các thư viện đã được cài đặt

    - name: 4. Verify file existence
      run: |
        echo "--- KIỂM TRA SỰ TỒN TẠI CỦA FILE ---"
        ls -la
        
    - name: 5. Check secrets are loaded
      run: |
        echo "--- KIỂM TRA BIẾN MÔI TRƯỜNG ---"
        if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
          echo "[LỖI] Secret SUPABASE_URL chưa được đặt."
          exit 1
        fi
        if [ -z "${{ secrets.SUPABASE_KEY }}" ]; then
          echo "[LỖI] Secret SUPABASE_KEY chưa được đặt."
          exit 1
        fi
        echo "[OK] Các secret đã được tải thành công."

    - name: 6. Run Scraper with Full Debug
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        PYTHONUNBUFFERED: "1" # Bắt buộc Python in ra log ngay lập tức
      run: |
        echo "--- BẮT ĐẦU CHẠY SCRIPT PYTHON ---"
        python -u scraper.py
